# Generated by Django 4.0.4 on 2022-04-19 09:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thehood', '0004_business_image_neighbourhood_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
