# Generated by Django 4.0.4 on 2022-04-19 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thehood', '0006_alter_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(default='True', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='image',
            field=cloudinary.models.CloudinaryField(default='True', max_length=255, verbose_name='image'),
        ),
    ]
